version: "3.9"

services:
  backend:
    build: ./backend
    container_name: mean-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mean-db
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: mean-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mean-mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: mean-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
